version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    hostname: 'localhost'
    environment:
      - RABBITMQ_DEFAULT_USER=aashayein
      - RABBITMQ_DEFAULT_PASS=aashayein
      - RABBITMQ_DEFAULT_VHOST=aashayein_vhost
    ports:
      - "5672:5672"
      - "8055:15672"


  zipkin-server:
    image: 'openzipkin/zipkin'
    container_name: zipkin-server
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "8054:9411"


  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8051:8051"
    depends_on:
      - rabbitmq


  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - config-server


  zuul-gateway:
    container_name: zuul-gateway
    build:
      context: ./zuul-gateway
      dockerfile: Dockerfile
    ports:
      - "8052:8052"
    depends_on:
      - config-server
      - eureka-server


  hystrix-dashboard:
    container_name: hystrix-dashboard
    build:
      context: ./hystrix-dashboard
      dockerfile: Dockerfile
    ports:
      - "8053:8053"
    depends_on:
      - config-server
      - eureka-server

  
  employee-service:
    container_name: employee-service
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    depends_on:
      - config-server


  address-service:
    container_name: address-service
    build:
      context: ./address-service
      dockerfile: Dockerfile
    ports:
      - "8061:8061"
    depends_on:
      - config-server


  export-service:
    container_name: export-service
    build:
      context: ./export-service
      dockerfile: Dockerfile
    ports:
      - "8062:8062"
    depends_on:
      - config-server


  title-service:
    container_name: title-service
    build:
      context: ./title-service
      dockerfile: Dockerfile
    ports:
      - "8063:8063"
    depends_on:
      - config-server
      
  role-service:
    container_name: role-service
    build:
      context: ./role-service
      dockerfile: Dockerfile
    ports:
      - "8064:8064"
    depends_on:
      - config-server


  mail-service:
    container_name: mail-service
    build:
      context: ./mail-service
      dockerfile: Dockerfile
    ports:
      - "8065:8065"
    depends_on:
      - config-server


  oauth-server:
    container_name: oauth-server
    build:
      context: ./oauth-server
      dockerfile: Dockerfile
    ports:
      - "8056:8056"
    depends_on:
      - config-server