zuul:
  prefix: "/api"
  ignoredServices: '*'
  routes:
    employee-service:
      path: /employee-service/**
      service-id: employee-service
      strip-prefix: true
    export-service:
      path: /export-service/**
      service-id: export-service
      strip-prefix: true
    address-service:
      path: /address-service/**
      service-id: address-service
      strip-prefix: true